name = "CalPin"
uuid = "5bb32001-22ba-47f2-9620-cd05ab76af38"
authors = ["Renilson Lisboa Júnior <renilsonlisboajunior@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QML = "2db162a6-7e43-52c3-8d84-290c1c42d82a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
